app_extra:
    resource: .
    type: extra

home:
    path: /
    controller: App\Controller\Open\HomeController::index

mail:
    path: /mail
    controller: App\Controller\Open\HomeController::mail



# zona privada
register:
    path: /register
    controller: App\Controller\Common\UserController::register
    name_prefix: _private
    # defaults: {_controller: app.common.user_controller}

login:
    path: /login
    controller: App\Controller\Common\SecurityController
    # defaults: {_controller: app.common.security_controller}

react:
    path: /react
    controller: App\Controller\Restrict\ReactController

users:
    path: /users
    controller: App\Controller\Common\UserController::index

logout:
    path: /logout