app_extra:
    resource: .
    type: routes_api

home:
    path: /
    controller: App\Controller\Open\HomeController::index

mail:
    path: /mail
    controller: App\Controller\Open\HomeController::mail

# zona comun
login:
    path: /login
    controller: App\Controller\Common\SecurityController::login

check-login:
    path: /check-login
    controller: App\Controller\Common\SecurityController::check_login
    methods: POST
    defaults:
        _format: json

logout:
    path: /logout

# zona privada
register:
    path: /register
    controller: App\Controller\Common\UserController::register
    name_prefix: _private

adminx:
    path: /adminx
    controller: App\Controller\Restrict\ReactController
admin:
    path: /admin/{reactslug}
    defaults: { _controller: App\Controller\Restrict\ReactController, reactslug: null }
    requirements:
        reactslug: ".+"
        
react:
    path: /react
    controller: App\Controller\Restrict\ReactController

users:
    path: /users
    controller: App\Controller\Common\UserController::index
