# proyecto\config\packages\dev\web_profiler.yaml
web_profiler:
    toolbar: true
    intercept_redirects: true #activa el toolbar

framework:
    profiler: 
        collect: false
        # { only_exceptions: false }
